### ISSUE TITLE
你好，可以简单说说这个定时任务系统的原理呢？

### ISSUE THREAD

**Issue by xuanskyer** [lisijie/webcron#1]
你好，可以简单说说这个定时任务系统的原理呢？

**Comment by lisijie** [comment]
用的是第三方的任务调度库，详情请看：https://github.com/robfig/cron

**Comment by joviqiao** [comment]
你好，为什么会选用这个呢？ 效率最好？ 要是服务器重启了怎么保证任务依然能够执行？

**Comment by lisijie** [comment]
貌似只有这个，呵呵。重启的话会重新加载已开启的任务。
