### ISSUE TITLE
 undefined: syscall.Statfs

### ISSUE THREAD

**Issue by sunger** [lisijie/webcron#2]
win7下执行命令：go get github.com/lisijie/webcron
如下错误：

C:\Users\vsunger>go get github.com/lisijie/webcron
# github.com/lisijie/webcron/app/libs

C:\gowks\wks\src\github.com\lisijie\webcron\app\libs\sys.go:15: undefined: syscall.Statfs_t
C:\gowks\wks\src\github.com\lisijie\webcron\app\libs\sys.go:16: undefined: syscall.Statfs

**Comment by lisijie** [comment]
不好意思，暂不支持windows
