### ISSUE TITLE
无法停止脚本

### ISSUE THREAD

**Issue by keyganker** [lisijie/webcron#3]
我执行了一个很简单的脚本，

```
<?php
    echo "start:   " . time() . "\n";
    sleep(3);
    echo "end:     " . time() . "\n";
```

执行一会儿之后点击暂停无法停止
点击暂停后的http是302
![image](https://cloud.githubusercontent.com/assets/3198806/12386970/417467d4-be04-11e5-9075-ddb07f7476ad.png)

**Comment by bannerchi** [comment]
task log 是什么样的？

**Comment by lisijie** [comment]
已经修复

**Comment by keyganker** [comment]
攫取了一段task log：
start:   1458645159
end:     1458645162
start:   1458645162
end:     1458645165
start:   1458645165
end:     1458645168
start:   1458645168
end:     1458645171
start:   1458645171
end:     1458645174
start:   1458645174

看到楼主已经修复了，能说明一下是因为什么原因吗？
