### ISSUE TITLE
安装失败，报undefined: beego.URLFor

### ISSUE THREAD

**Issue by manofphysics** [lisijie/webcron#8]
# github.com/lisijie/webcron/app/controllers

gocode/src/github.com/lisijie/webcron/app/controllers/base.go:60: undefined: beego.URLFor
gocode/src/github.com/lisijie/webcron/app/controllers/base.go:73: this.TplName undefined (type *BaseController has no field or method TplName)
gocode/src/github.com/lisijie/webcron/app/controllers/base.go:105: this.ServeJSON undefined (type *BaseController has no field or method ServeJSON)
gocode/src/github.com/lisijie/webcron/app/controllers/group.go:25: undefined: beego.URLFor
gocode/src/github.com/lisijie/webcron/app/controllers/main.go:97: undefined: beego.URLFor
gocode/src/github.com/lisijie/webcron/app/controllers/main.go:101: undefined: beego.URLFor
gocode/src/github.com/lisijie/webcron/app/controllers/main.go:110: undefined: beego.URLFor
gocode/src/github.com/lisijie/webcron/app/controllers/main.go:149: undefined: beego.URLFor
gocode/src/github.com/lisijie/webcron/app/controllers/main.go:153: undefined: beego.URLFor
gocode/src/github.com/lisijie/webcron/app/controllers/main.go:157: this.TplName undefined (type *MainController has no field or method TplName)
gocode/src/github.com/lisijie/webcron/app/controllers/main.go:157: too many errors

**Comment by lisijie** [comment]
需要升级beego到最新版本
go get -u github.com/astaxie/beego
