### ISSUE TITLE
锁阻塞后续任务

### ISSUE THREAD

**Issue by kran** [lisijie/webcron#9]
选择同一个任务只能有一个实例时，第一个任务执行时，后续任务会全部阻塞住，而不是忽略、
比如：
任务为sleep(10)
任务频率为1s
那么第一个任务会阻塞住全部后续任务。10秒后第二个任务执行，而后续还有9个任务在等待。

**Comment by wuzhizhan** [comment]
个人认为正确的逻辑应该是忽略后面的九个

**Comment by lisijie** [comment]
收到。已经修复。
